### ISSUE TITLE
Telescience Layout Problems

### ISSUE THREAD

**Issue by Allyriadil** [ZomgPonies/OldParadise#133]
After the telescience layout change several things are not working correctly. 
- The windoor cannot be opened with a scientist ID
- The air control computer for the scrubbers still lists 4 instead of 2

It would also be nice if the teleporter could be moved in front of the room.

**Comment by ghost** [comment]
The scrubber control lists 4 instead of 2 because there are 2 scrubbers in toxins storage, and it detects any large scrubbers within a 25 tile radius. The issue with the windoors will be fixed in my next update.

**Comment by ZomgPonies** [comment]
Fixed
