### ISSUE TITLE
Two R&D design related issues

### ISSUE THREAD

**Issue by Midaychi** [ZomgPonies/OldParadise#202]
Any machine frame recipe that uses cable coils in it cannot be completed, as cable coils cannot be placed into them.
Also, the robotics R&D console is actually just a core r&d console with special map defines to make it robotics access with the robotics wing of the design server. This means that it cannot be reconstructed by a player. Even just screwing it offline and screwing it back online will turn it into an R&D core console that requires tox access and uses the R&D wing of the design servers.

**Comment by ZomgPonies** [comment]
Fixes
