### ISSUE TITLE
Projectiles deal double damage because of broken pooling

### ISSUE THREAD

**Issue by Walter0o** [ZomgPonies/OldParadise#205]
I noticed sometimes guns deal double damage to mobs and structures like windows.
For example a beam with 40 damage delt 80, a bullet with 15 damage delt 30, etc.
After some more experimentation it appeared this bug does not always happen, so i suspected the object pool system not properly recycling the beams and bullets sometimes,
which in turn impact twice into the target then.
I disabled object pooling for all projectile objects and it fixed the issue.
I wanted to report it to the /vg/ devs who wrote the object pool, but it appears they reverted their pooling already : 

https://github.com/d3athrow/vgstation13/commit/7243a36f1ecfd89a85c6493c0f95a1d0170e8728

This being said, i don't think pooling will help much with anything considering the BYOND devs are working on fixing the inefficiency of spawning and deleting objects,  and more unexpected behaviour could occur from the pool and create more hard-to-track bugs.

So i completely removed it from my build, simply replacing the procs in code__HELPERS\experimental.dm : 

```
/proc/getFromPool(const/A, const/B)
    return new A(B)
```

and

```
/proc/returnToPool(const/A)
    if (!istype(A, /atom/movable))
        return -1
    del(A)
```

Feel free to do so too, but atleast merge the /vg/ commits so your players don't get oneshotted because of bugs.

**Comment by ZomgPonies** [comment]
Used deathrow's commit to revert for now, will use your code if I need to rip the whole system out.
