### ISSUE TITLE
Vox not starting with a nitrogen tank on nukeops

### ISSUE THREAD

**Issue by Uso15** [ZomgPonies/OldParadise#295]
Rolled Nuke ops as a Vox, didn't spawn with a nitrogen tank, just a turtleneck suit.

**Comment by W3bster** [comment]
Couldn't find what makes Vox spawn with nitrogen gear. Would it be possible to make it have a custom load out for that species in the gamemode file?
[An example of such loadout](http://pastebin.com/raw.php?i=3Bc3VvYt)

**Comment by VampyrBytes** [comment]
As an fyi, the bit that makes Vox spawn with Nitro gear is at the start of item_spawning.dm

Couldn't use that as it would have put the tank on the back, which would have led to Vox starting with no backpack, or the gear nuke ops start with in the backpack, so they now spawn with the tank in their hand

In your loadout you change their suit etc. This isn't needed as by default all races can wear syndie gear... once it's created and put on a different race it's then marked as only wearable for that race. It also would have meant that nuke ops Vox had an advantage, as they wouldn't have the bright red suit

Other than that you were on the right lines - effectively what I've done is a mini loadout, just giving vox the mask and tank and turning their internals on

I also put a Nitro canister on the syndie ship for them
