### ISSUE TITLE
Changeling Regeneration

### ISSUE THREAD

**Issue by W3bster** [ZomgPonies/OldParadise#300]
##### Possibly affected files

> code/game/gamemodes/changeling/changeling_powers.dm
> LINE 451

When using the Return To Life verb, all damage types are healed as expected and the Chemical amount (20) is removed as per expected. **Yet the previously removed verbs at line 532 are not given back, and the player cannot get back up.**

**Comment by Regen1** [comment]
Looked into it, looks like the code stops at line 506 or something.
Probably has something to do with https://github.com/ZomgPonies/Paradise/commit/34712ecc3779ccc73cc3cd233a5a241ea9a9bfe3

**Comment by VampyrBytes** [comment]
I'll have a look and see what's going on... calls for internal_organs[organ_name] won't work, so I guess the problem comes from that now working

**Comment by VampyrBytes** [comment]
ok, god knows why it was trying to get the organs that way anyway
