### ISSUE TITLE
Station Blueprints

### ISSUE THREAD

**Issue by Artorp** [ZomgPonies/OldParadise#336]
**Brief description of the issue**: Station Blueprints unable to define new area.

**What you expected to happen**: Using blueprints in confined area in space should create a new area.

**What actually happened**: Area is created... Somewhere. Not where you want it though.

**Steps to reproduce**:Grab Station Blueprints, go to space, make airtight room, use blueprints, create new area.

**Additional info**: Using Jump-to-Area will show the new area in a list, but jumping to it yields a random location. Here's an open issue for Baystation12: Baystation12/Baystation12#5796

**Comment by W3bster** [comment]
Suggesting issue be closed due to fix.

**Comment by alex-gh** [comment]
Closed via #368
