### ISSUE TITLE
Can not target a UI spot with any item.

### ISSUE THREAD

**Issue by IndexLP** [ZomgPonies/OldParadise#404]
This is the error message and the stack trace:

runtime error: undefined variable /obj/item/weapon/tank/emergency_oxygen/var/rig_restrict_helmet
proc name: attack ui (/mob/proc/attack_ui)
    source file: mob.dm,113
    usr: Patrick Fischer (/mob/living/carbon/human/human)
    src: Patrick Fischer (/mob/living/carbon/human/human)
call stack:
Patrick Fischer (/mob/living/carbon/human/human): attack ui(15)
the storage1 (/obj/screen/inventory): Click(null, "mapwindow.map", "icon-x=16;icon-y=12;left=1;scr...")

This error applies to more than just oxy-tanks, no item can be placed in a UI spot.

This issue does not seem to affect the live server, so I should suspect that it's from the recent changes to hardsuits.

**Comment by Bone-White** [comment]
I've locally stopped the runtime error (missed a varcheck line) but I'm unsure as to why the suit storage won't work.  I don't have the time to properly test this now however.  Does this only apply to eva hardsuits?

**Comment by IndexLP** [comment]
I was not wearing a hard-suit at all when I discovered the error, just trying to put an emergency oxygen tank on a belt slot. And then I tested other slots (and other items) and could not place in them either.

I was able to place things into bags, but not any UI slot. I think the error that caused the undefined variable also ended the proc (/mob/proc/attack_ui) early when it happened which means it would not have placed the item into a slot. Assuming you have fixed the undefined variable error by checking if it exists first I would be willing to bet that fixes the inability to slot an item through the UI and would resolve this issue. (I also cant test right now unfortunately)

**Comment by IndexLP** [comment]
This issue still persists, and is in my opinion a critical issue. While items may be placed in any slot that is toggled open by clicking the backpack with the arrow at the top right (any body slot) they cannot be placed in any of these slots by clicking on the UI (although the ctrl+e hotkey still works):
- Suit storage
- ID
- Belt
- Back
- Storage1/Storage2
- PDA

**Comment by ghost** [comment]
You seem to be able to place small clothing items like Gloves into some of those UI slots

**Comment by VampyrBytes** [comment]
fixed with #415
