### ISSUE TITLE
Map edit pull requests need guidelines

### ISSUE THREAD

**Issue by mvanalphen** [ZomgPonies/OldParadise#480]
Notifying @Fox-McCloud. 

The repo really needs guidelines on map edits. Pull request https://github.com/ZomgPonies/Paradise/pull/471 caused about 13,000 line changes to the map file (which is basically the entire file) even though it only changed three areas. This means that anyone else making map changes will have their work discarded completely due to the merge conflicts this causes, which has happened to me twice now. 

As such, every map change needs to be done using the mapmerge tool, which was built to fix this issue, and otherwise should be denied. For more information: http://www.ss13.eu/wiki/index.php/Map_Merger

This can't be applied retroactively easily either, making it critical that people use the tool.

**Comment by fj45** [comment]
I agree, it will be far easier to just be able to use the tool then have to track down everyone doing any kind of mapping and making sure I won't end up conflicting with anyone else.

**Comment by PJB3005** [comment]
Yep, mapmerger is really needed, BYOND and it's map format *grumbles

BTW, I know it's of topic, but don't link to SS13.eu anymore, tgstation13.org is the new /tg/ site
